@startuml
class Gebruiker {
    + Nummer : int <<get>> <<set>>
    + Voornaam : string <<get>> <<set>>
    + Familienaam : string <<get>> <<set>>
    + Gebruiker()
    + Wissen() : void
    + ToonGegevens() : string
}
@enduml
